---
apiVersion: v1
kind: Namespace
metadata:
  name: bitnami-external-dns

---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: external-dns
  namespace: bitnami-external-dns
spec:
  interval: 2m
  url: https://charts.bitnami.com/bitnami

---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: external-dns
  namespace: bitnami-external-dns
spec:
  chart:
    spec:
      chart: external-dns
      sourceRef:
        kind: HelmRepository
        name: external-dns
  interval: 2m
  install:
    remediation:
      retries: 3
  uninstall:
    timeout: 5m
    disableHooks: false
    keepHistory: false
  values:
    provider: aws
    interval: 30s
    logLevel: info
    policy: sync
    serviceAccount:
      create: false
      name: bitnami-external-dns-controller